### PR TITLE
Refactor `VersionedConfig` - 1.0.0

### PR DESCRIPTION
**Pull request by its-miroma**
This is a **breaking** change! The structure of settings has changed.

Changes: See commit messages

TODOs: Grep "TODO" in code, mainly ~~sidebars and~~ nav items are not working

### CODE REVIEW

**Comment by IMB11** [comment]
I might as well refactor the test docs into an actual docs site after this PR. 0.11.0 and 1.0.0 versions

**Review by IMB11 — COMMENTED** [review]
This is really good, Im going to try and tackle the navbar versioning and convert the test documentation into the actual documentation for this plugin.

**Comment by its-miroma** [comment]
If you're working on the nav bar items, I want to leave a feature request here: maybe the switcher should have an option for a prefix-suffix combo with the version, so that you can show something like "Version 1.0.0 🔽".

I tried to implement it, but all nav bars for the versions were the same, so it wasn't possible

**Comment by its-miroma** [comment]
> convert the test documentation into the actual documentation for this plugin.

I think you/I should do that later, let's release asap to be ready for `fabric-docs`

**Comment by IMB11** [comment]
Nah, I have tons of time after this week, im willing to delay a little bit :)

**Comment by IMB11** [comment]
And to be honest, i've finished writing 3/4 of the docs already lol

**Comment by IMB11** [comment]
Alright, once you've translated to italian, we should be ready to merge.

**Comment by IMB11** [comment]
Actually, feel free to PR the italian to a seperate PR. Will just make a "test" language for now, I dont have the time to translate everything into french.

**Pull request merged**
